import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import { cookies } from "next/headers";
import { getMe } from "@/utils/services";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = await cookies();
  const token = cookiesStore.get("accessToken");
  const user = await getMe(token?.value || "");

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
      </head>
      <body className={`${inter.variable} font-inter bg-main text-white h-dvh lg:!px-8 relative overflow-hidden !max-w-[1440px] !mx-auto`}>
        <Provider user={user} token={token?.value || ""}>
          {children}
        </Provider>
      </body>
    </html>
  );
}
